### ISSUE TITLE
API down: error 500

### ISSUE THREAD

**Issue by EndBug** [Fuyukai/OWAPI#281]
## Issue

API returns a 500 error (`IndexError('list index out of range',)`) when requesting a public account (seems to work as expected when requesting a private account).

## Links that cause the issue

`https://owapi.net/api/v3/u/Kharumaan-2976/blob`
`https://owapi.net/api/v3/u/EndBug-2119/blob`

**Comment by EndBug** [comment]
Seems to be ok now

**Comment by EndBug** [comment]
The problem seems to be back with the same error:

```json
{"msg": "please report this!", "exc": "IndexError('list index out of range',)", "error": 500}
```

**Comment by EndBug** [comment]
Update: it seems to be random

**Comment by relaera** [comment]
@EndBug - You probably don't need to keep re-opening this issue. The Blizzard website has been up and down (verify https://playoverwatch.com/en-us/career/pc/EndBug-2119 and https://playoverwatch.com/en-us/career/pc/Kharumaan-2976 are working as you'd expect).

When it's down, the API is going to generate a LOT of errors because it's searching for elements that don't exist. If you see a message saying "I NEED HEALING" on the website, that's probably the cause.

At this point, everything points to issues on Blizzard's end, which we can't fix

**Comment by EndBug** [comment]
Sorry, my bad, I'm closing the issue (once and for all)
