### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Downy** [Fuyukai/OWAPI#287]
## Issue

IndexError('list index out of range',)

## Links that cause the issue

`https://owapi.net/api/v3/u/GlenMaiden-1699/blob`

**Comment by relaera** [comment]
This is due to a somewhat recent change from the Blizzard website side where the Competitive Play selector is disabled if an account doesn't have any competitive play time. It's attempting to enumerate hero information for competitive, and it can't.

I'll look into this to see if I can fix it, but for the sake of hero stats, people typically benchmark their competitive play statistics because that tends to be a little more representative of performance.

**Comment by relaera** [comment]
As a workaround, you can grab from the `GlenMaiden-1699/stats` endpoint, `GlenMaiden-1699/heroes/quickplay` endpoint, or `GlenMaiden-1699/achievements` to grab the info that you're looking for

**Comment by jpylypiw** [comment]
It seems like the Account has played some Competitive now.
Maybe we get another Example Account to examine this issue?

**Comment by Downy** [comment]
Here's another broken one
https://owapi.net/api/v3/u/romanthewizard/blob?platform=psn
